name: Publish Docker image

on:
  push:
    branches: [main]
    tags: ["*.*.*"]

jobs:
  docker-release:
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/docker-release.yml@c4caf23ade98668434145f5b1abd3bc42cec63e7
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
      security-events: write
    secrets: inherit
