name: Publish Docker image

on:
  push:
    branches: [main]
    tags: ["*.*.*"]

jobs:
  docker-release:
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/docker-release.yml@d2a2353830cf211a9f18f3585085016766294dff
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
      security-events: write
    secrets: inherit
