name: Publish Docker image

on:
  push:
    branches: [main]
    tags: ["*.*.*"]

jobs:
  docker-release:
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/docker-release.yml@fb907a46b00693a117ca6b975da6e7b0f8238491
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
      security-events: write
    secrets: inherit
